---
# SPDX-FileCopyrightText: none
# SPDX-License-Identifier: CC0-1.0
# SPDX-FileType: SOURCE
coverage:
  status:
    project:
      default:
        threshold: 10%
    patch:
      default:
        threshold: 20%
