---
# SPDX-FileCopyrightText: (c) 2021 ale5000
# SPDX-License-Identifier: GPL-3.0-or-later
# SPDX-FileType: SOURCE
name: "Periodic security checks"
on:
  schedule:
    - cron: "0 0 * * 1"
  pull_request:
jobs:
  base-job:
    name: "Periodic security checks"
    runs-on: ubuntu-latest

    steps:
      - name: "Check out code"
        uses: actions/checkout@v3
        with:
          fetch-depth: "0"
      - name: "Gradle Wrapper validation"
        uses: gradle/wrapper-validation-action@master
      - name: "Gitleaks"
        uses: zricethezav/gitleaks-action@v1
